export const actionTypes = {
  ADD_POST: 'ADD-POST',
  SEND_MESSAGE: 'SEND-MESSAGE',
  UPDATE_NEW_POST_TEXT: 'UPDATE-NEW-POST-TEXT',
  UPDATE_NEW_MESSAGE_TEXT: 'UPDATE-NEW-MESSAGE-TEXT',
  SET_USERS: 'SET-USERS',
  SET_PROFILE_INFO: 'SET-PROFILE-INFO',
  SET_CURRENT_PAGE: 'SET-CURRENT-PAGE',
  SET_IS_LOADING: 'SET-IS-LOADING',
  SET_USERS_TOTAL: 'SET-USERS-TOTAL',
  FOLLOW: 'FOLLOW',
  UNFOLLOW: 'UNFOLLOW',
}
